language: cpp
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc-5
  - clang

env:
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On"
  matrix:
    - CMAKE_CONFIGURATION=release BUILD_DIR=build
    - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake3
      - cppcheck
      - clang-tidy-3.8
      - g++-5
      - libfreetype6-dev
      - libpng-dev

before_install:
  # libpng is already installed by default
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cppcheck freetype; fi
  - chmod +x ./configure

before_script:
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
  - cmake --build $BUILD_DIR --target check-all
